type Query {
  hello: String

  now: Instant!

  named(name: String!): Named
}

type Subscription {
  tick: Instant!
}

scalar Instant

interface Named {
  name: String!
}

type User implements Named {
  name: String!
}

type Pet implements Named {
  name: String!
  species: String!
}
